# Site settings
title: Natali Vlatko - natali.com.au
email: natalivlatko@gmail.com
description: Hello, my name is Natali Vlatko and I’m a Writer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://natali.com.au"
twitter_username: natalisucks

# Build settings
markdown: kramdown
